### A CI workflow template that runs linting and python testing

name: Test tap-googleads

on:
  push:
    branches: [main]
    paths-ignore: [README.md]
  pull_request:
    paths-ignore: [README.md]

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      id: setup-python
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install uv
      uses: astral-sh/setup-uv@d9e0f98d3fc6adb07d1e3d37f3043649ddad06a1 # v6.5.0
    - name: Test with pytest
      env:
        PYTEST_ADDOPTS: --ignore tap_googleads/tests/test_core.py
        UV_PYTHON: ${{ steps.setup-python.outputs.python-path }}
      run: |
        uv run pytest
